Fix some mistakes and flesh out the usage with some comments

diff --git a/.local/bin/asr b/.local/bin/asr
--- a/.local/bin/asr
+++ b/.local/bin/asr
@@ -1,5 +1,9 @@
 #!/bin/bash
+
 # asr <package>
+
+# Download official Arch Linux PKGBUILDs and source files directly from the
+# svntogit repositories.
 
 # Oh boy, here we go!
 pkgname="$1"
@@ -25,10 +29,9 @@ done
 
 # Fail if we've gone through the array elements without success
 if ((!status)); then
-    printf >&2 "%s\n" "Cannot locate the package: $pkgname."
+    printf >&2 "%s\n" "Cannot locate: $pkgname."
     exit 1
 fi
-
 
 # Checkout trunk and clean up left overs
 if [[ -d "$pkgname" ]]; then
diff --git a/.local/bin/scred b/.local/bin/scred
--- a/.local/bin/scred
+++ b/.local/bin/scred
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# A very basic wrapper around `ffmpeg` to quickly record the screen at a
+# predefined time.  Codec used is based on file extension.
+
 if (($# < 3)); then
     printf "%s\n" "scred -t <time> -d [xorg display] -s [size] <outfile.ext>"
 fi
@@ -15,9 +18,11 @@ while getopts "t:d:s:r:" argv; do
         r)
             recrate="$OPTARG" ;;
         \?)
-            printf >&2 "%s\n" "Invalid Option: -$OPTARG" ;;
+            printf >&2 "%s\n" "Invalid Option: -$OPTARG"
+            exit 1 ;;
     esac
 done
+# shift off the rest of the arguments to "$@"
 shift $((OPTIND-1))
 
 ffopts=(
