asr: Small changes, make note of pkgbase and pkgname distinctions.

diff --git a/.local/bin/asr b/.local/bin/asr
--- a/.local/bin/asr
+++ b/.local/bin/asr
@@ -8,15 +8,14 @@
 pkgname="$1"
 
 # A bit of future-proofing
-urls=("git://projects.archlinux.org/svntogit/packages.git"
-      "git://projects.archlinux.org/svntogit/community.git")
+urls=('git://projects.archlinux.org/svntogit/packages.git'
+      'git://projects.archlinux.org/svntogit/community.git')
 
 status="${#urls[@]}"
 for url in "${urls[@]}"; do
     # Determine which repository the package exists in
     if git ls-remote --exit-code "$url" refs/heads/packages/"$pkgname"; then
         git clone --no-checkout --branch packages/"$pkgname" --single-branch "$url" "$pkgname"
-
         # Break out if we succeed to avoid duplicate packages being found.
         break
     else
@@ -26,7 +25,8 @@ done
 
 # Fail if we've gone through the array elements without success
 if ((!status)); then
-    printf >&2 "Cannot locate: %s.\n" "$pkgname"
+    printf >&2 '%s: cannot locate package.\n' "$pkgname"
+    printf >&2 'Make sure the pkgname is not from a split-package\n'
     exit 1
 fi
 
@@ -36,6 +36,6 @@ if [[ -d "$pkgname" ]]; then
     git checkout HEAD:trunk -- .
 else
     # This should never happen
-    printf >&2 "Directory does not exist.\n"
+    printf >&2 'Directory does not exist.\n'
     exit 1
 fi
