startx: Some cleanups

diff --git a/.local/bin/startx b/.local/bin/startx
--- a/.local/bin/startx
+++ b/.local/bin/startx
@@ -3,22 +3,29 @@
 # Alternative, simpler startx which makes use of the XDG specification and
 # eventually systemd
 
-# Make sure we aren't running in an xserver
+# Make sure we aren't running in an xserver.
 if [[ -n "$DISPLAY" ]]; then
     exit 1
 fi
 
-confdir="${XDG_CONFIG_HOME:-$HOME/.config}"
-#cachedir="${XDG_CACHE_HOME:-$HOME/.cache}"
+readonly confdir="${XDG_CONFIG_HOME:-$HOME/.config/X11}"
+#readonly cachedir="${XDG_CACHE_HOME:-$HOME/.cache/X11}"
+readonly rundir="$XDG_RUNTIME_DIR"/X11
 
-xinitrc="${XINITRC:-$confdir/X11/}"/xinitrc
+# Make any necessary directories, bail if any fail.
+if ! mkdir -p "$confdir" "$rundir"; then
+    exit 1
+fi
+
+xinitrc="${XINITRC:-$confdir}"/xinitrc
 #log="$cachedir"/X11/xsession.log
 
-export XAUTHORITY="$XDG_RUNTIME_DIR"/X11-authority
+export XAUTHORITY="$rundir"/xauthority
 
-# Delete this when using systemd and dbus.socket/service
+# Delete this when using systemd and dbus.socket/service.
 unset DBUS_SESSION_BUS_ADDRESS
 
+# E.g. ICE Authority stuff.
 unset SESSION_MANAGER
 
 if [[ -n "$XDG_VTNR" ]]; then
@@ -28,10 +35,10 @@ else
     exit 1
 fi
 
-# I can blindly add a new entry with xauth because this is stored in a tmpfs
+# I can blindly add a new entry with xauth because this is stored in a tmpfs.
 xauth -q add "$DISPLAY" . "$(mcookie)" &> /dev/null
 
-# # If using systemd --user with dbus.service
+# # If using systemd --user with dbus.service.
 # sysdopts=(
 #     --user
 #     --scope
