lots of inconsequential changes; move vimperator runtime to localdir/data

diff --git a/local/bin/abihck b/local/bin/abihck
--- a/local/bin/abihck
+++ b/local/bin/abihck
@@ -17,20 +17,21 @@ err() {
 replicate_install() {
     local pname=$1
     local version=$2
+    local package=/var/cache/pacman/pkg/"$pname"-"$version"-"$arch".pkg.tar.xz
 
-    if ! bsdtar -xvf /var/cache/pacman/pkg/"$pname"-"$version"-"$arch".pkg.tar.xz -C abi/"$pname"/"$version"; then
-        err 'Extraction failed'
+    if ! bsdtar -xvf "$package" -C abi/"$pname"/"$version"; then
+        err 'extraction failed'
     fi
 }
 
 print_version() {
     local pname=$1
-    expac '%v' "$pname" || err "No version found for $pname"
+    expac '%v' "$pname" || err '%s: no version found' "$pname"
 }
 
 check_package_exists() {
     local pname=$1
-    pacman -T "$pname" || err 'No such package found'
+    pacman -T "$pname" || err 'no such package found'
 }
 
 dump_version() {
@@ -49,7 +50,7 @@ dump_version() {
     )
 
     if ! abi-compliance-checker "${options[@]}"; then
-        err 'Failed to dump first version'
+        err 'failed to dump first version'
     fi
 }
 
@@ -90,7 +91,7 @@ compare_abi_dumps() {
     )
 
     if ! abi-compliance-checker "${options[@]}"; then
-        err 'Failed to compare abi'
+        err 'failed to compare abi'
     fi
 }
 
@@ -114,7 +115,7 @@ check_api_sanity() {
     fi
 
     if ! (cd abi && api-sanity-checker "${options[@]}"); then
-        err 'Failed to check api sanity'
+        err 'failed to check api sanity'
     fi
 }
 
@@ -142,7 +143,7 @@ while (($#)); do
     case $1 in
         -m) makepkg=1 ;;
         -a) shift; arch=$1 ;;
-        -h) puts 'usage: abihck [-m] [-a arch] <package_name>'
+        -h) puts 'usage: abihck [-m] [-a arch] pkgname'
             puts '       -m  Use makepkg and repose update before system update'
             puts '       -a  Select architecture: i686, x86_64 or any (defaults to x86_64)'
             exit ;;
@@ -165,7 +166,7 @@ update_system
 
 new_version=$(print_version "$pname")
 if [[ $new_version == "$old_version" ]]; then
-    err 'Versions are the same?'
+    err 'same versions'
 fi
 
 mkdir -p abi/"$pname"/"$new_version"
diff --git a/local/data/plaid/cleanup b/local/data/plaid/cleanup
--- a/local/data/plaid/cleanup
+++ b/local/data/plaid/cleanup
@@ -1,22 +1,24 @@
 #!/bin/bash
+# cleanup - utility to clear out playlist files with no matching menu entry
 
 dir=${XDG_DATA_HOME:-$HOME/.local/share}/plaid/playlists
 
 in_array() {
-    local i
+	local mark=$1
+	local element
 
-    for i in "${@:2}"; do
-        if [[ $1 == $i ]]; then
+	for element in "${@:2}"; do
+		if [[ $element == "$mark" ]]; then
             return 0
         fi
-    done
-    # No match
-    return 1
+	done
+
+    # Mark not found.
+	return 1
 }
 
-[[ ! -s plaid_menu ]] && exit
+[[ -s plaid_menu ]] || exit
 
-# Build an array of playlists found in the actual dmenu menu
 while IFS='=' read -r k v; do
     if ! [[ $k =~ ^Title|^Command ]]; then
         playlists+=("$v")
@@ -26,8 +28,6 @@ done < plaid_menu
 
 files=("$dir"/*)
 
-# Check if any of the files that exist are also in the menu, remove those which
-# aren't
 for i in "${files[@]}"; do
     if ! in_array "$i" "${playlists[@]}"; then
         rm -vf -- "$i"
