asr: fix the case of perl but break gtk3

diff --git a/local/bin/asr b/local/bin/asr
--- a/local/bin/asr
+++ b/local/bin/asr
@@ -1,7 +1,7 @@
 #!/bin/bash
 # asr - download arch linux build files from the svntogit repositories
 
-# requires git pacsift expac 
+# requires git pacsift expac
 
 if ((!$#)); then
     printf 'usage: asr package\n' >&2
@@ -10,9 +10,15 @@ fi
 
 package=$1
 
-# Before doing anything check if the requested package is provided by something
-# else.
-providers=($(pacsift --sync --provides="$package"))
+# First see if we can get any exact matches as only listing providers can miss
+# them.
+providers=($(pacsift --sync --name "$package"))
+
+# Fallback on searching for providers instead, this is necessary for most perl
+# packages.
+if [[ ! ${providers[*]} ]]; then
+    providers=($(pacsift --sync --provides="$package"))
+fi
 
 # Give the user the option to pick which package they might be refering to if
 # we get more than one match.
@@ -23,6 +29,8 @@ if ((${#providers[@]} > 1)); then
     done
     # Remove leading "repo/" text added by pacsift.
     package=${pkg#*/}
+else
+    package=${providers#*/}
 fi
 
 # Finally check if the package is part of a split-package by checking if it has
@@ -33,28 +41,25 @@ if [[ $pkgbase != '(null)' ]]; then
     package=$pkgbase
 fi
 
-repos=('git://git.archlinux.org/svntogit/packages.git'
-       'git://git.archlinux.org/svntogit/community.git')
+# At this point if package is still not set we must have failed to find
+# anything.
+if [[ ! $package ]]; then
+    printf '%s: cannot locate package\n' "$1" >&2
+    exit 1
+fi
 
-status=${#repos[@]}
+repos=('git://projects.archlinux.org/svntogit/packages.git'
+       'git://projects.archlinux.org/svntogit/community.git')
+
 for repo in "${repos[@]}"; do
     # Determine which repository the package exists in.
     if git ls-remote --exit-code "$repo" refs/heads/packages/"$package"; then
         git clone -nb packages/"$package" --single-branch "$repo" "$package"
         # Break out if we succeed to avoid duplicate packages being found.
         break
-    else
-        ((--status))
     fi
 done
 
-# Fail if we've gone through the array elements without success.
-if ((!status)); then
-    printf '%s: cannot locate package\n' "$package" >&2
-    exit 1
-fi
-
-# Checkout trunk and clean up left overs.
 if cd "$package"; then
     git checkout HEAD:trunk -- .
 fi
