retroarch-updater: trap cnorm, switch to localdir
I use civis to hide the cursor during git fetch for a nice updating
message, I do restore cnorm but this might not be run if the git fetch
is terminated for whatever reason; so trap it on any kind of exit.

This also switches to LOCALDIR

diff --git a/local/bin/retroarch-updater b/local/bin/retroarch-updater
--- a/local/bin/retroarch-updater
+++ b/local/bin/retroarch-updater
@@ -1,8 +1,21 @@
 #!/bin/bash
 # retroarch-updater - installs and updates retroarch cores
 
-readonly core_directory=${XDG_CONFIG_HOME:-$HOME/.config}/retroarch/core
+readonly core_directory=${LOCALDIR:-$HOME/local}/cfg/retroarch/core
 readonly build_directory=$core_directory/build
+readonly -A cores=(
+    [pcsx_rearmed]=pcsx_rearmed_libretro.so
+    [mgba]=mgba_libretro.so
+    [snes9x-next]=snes9x_next_libretro.so
+    [nestopia]=nestopia_libretro.so
+    [libretro-fba]=fb_alpha_libretro.so
+    [libretro-ppsspp]=ppsspp_libretro.so
+    #[mame]=mame_libretro.so
+)
+
+# Unconditionally restore the cursor at exit as the script might terminate
+# during git fetch where I hide it for aesthetic reasons.
+trap 'printf "\e[?12l\e[?25h" && exit' EXIT
 
 confirm() {
     local -l reply
@@ -19,19 +32,21 @@ check() {
 
     # git fetch will return 0 even if nothing was fetched meaning we need to
     # check regardless, meh.
-    printf -- '\e[1;33m %s\e[0m: Updating...\r' "$repo"
+    printf '\e[?25l\e[1;33m%s\e[0m: updating...\r' "$repo"
     git fetch 2> /dev/null
+    printf '\e[?12l\e[?25h'
 
     if [[ $(git rev-parse HEAD) != $(git rev-parse @{upstream}) ]]; then
-        printf -- '\e[1;33m%s\e[0m: Changes found:\n' "$repo"
+        printf '\e[1;33m%s\e[0m: changes found:\n' "$repo"
         git --no-pager log --oneline --stat ..@{upstream}
         if confirm 'Rebuild the core?'; then
-            git merge
-            build "$core"
+            if git merge; then
+                build "$core"
+            fi
             return
         fi
     else
-        printf -- '\e[1;32m %s\e[0m: Repository up to date.\n' "$repo"
+        printf '\e[1;32m%s\e[0m: repository up to date\n' "$repo"
     fi
 
     update "$core"
@@ -42,11 +57,20 @@ update() {
     local core=$1
 
     if [[ ! -e $core_directory/$core ]]; then
-        printf -- '\e[1;33m%s\e[0m: Not found.\n' "$core_directory/$core"
-        if confirm 'Attempt to build it anyway?'; then
+        printf '\e[1;33m%s\e[0m: not found\n' "$core_directory/$core"
+        if confirm 'attempt to build it anyway?'; then
             build "$core"
         fi
     fi
+}
+
+applyhacks() {
+    local core=$1
+
+    case $core in
+        ppsspp_libretro.so)
+            git submodule update --init lang native ext/armips ;;
+    esac
 }
 
 build() {
@@ -55,7 +79,7 @@ build() {
 
     # Libretro let this get out of hand and now we have to suffer for it.
     # https://github.com/libretro/libretro-super/issues/244
-    apply_hacks "$core"
+    applyhacks "$core"
 
     if [[ -e Makefile.libretro ]]; then
         make -f Makefile.libretro
@@ -72,27 +96,21 @@ build() {
     install "$core"
 }
 
-apply_hacks() {
-    local core=$1
-
-    case $core in
-        ppsspp_libretro.so) git submodule update --init lang native ext/armips ;;
-    esac
-}
-
 install() {
-    # Global: core_directory, build_directory
+    # global core_directory
+    # global build_directory
     local core=$1
 
     if [[ -e $core ]]; then
         mv -vf -- "$core" "$core_directory"
     else
-        printf -- '\e[1;31m%s\e[0m: No core found.  This might be the result of a build failure.\n' "$core"
-        printf -- 'Here is some state information:\n'
-        printf -- '    PWD=%s\n' "$PWD"
-        printf -- '    core=%s\n' "$core"
-        printf -- '    core_directory=%s\n' "$core_directory"
-        printf -- '    build_directory=%s\n' "$build_directory"
+        printf '\e[1;31m%s\e[0m: no core found\n' "$core"
+        printf '\nThis might be the result of a build failure\n'
+        printf 'Here is some state information:\n'
+        printf '    PWD=%s\n' "$PWD"
+        printf '    core=%s\n' "$core"
+        printf '    core_directory=%s\n' "$core_directory"
+        printf '    build_directory=%s\n' "$build_directory"
     fi
 }
 
@@ -104,24 +122,13 @@ process_core() {
     mkdir -p -- "$build_directory"
 
     if [[ ! -d $build_directory/$repo ]]; then
-        printf -- '\e[1;33m%s\e[0m: Core not present, attempting to clone...\n' "$repo"
-        git clone --depth 1 git://github.com/libretro/"$repo" "$build_directory/$repo"
+        printf '\e[1;33m%s\e[0m: core not found, cloning...\n' "$repo"
+        git clone --depth 1 https://github.com/libretro/"$repo" "$build_directory/$repo"
     fi
 
     (cd "$build_directory/$repo" && check "$repo" "$core")
 }
 
-declare -A cores
-readonly cores=(
-    [pcsx_rearmed]=pcsx_rearmed_libretro.so
-    [mgba]=mgba_libretro.so
-    [snes9x-next]=snes9x_next_libretro.so
-    [nestopia]=nestopia_libretro.so
-    [libretro-fba]=fb_alpha_libretro.so
-    [libretro-ppsspp]=ppsspp_libretro.so
-    [mame]=mame_libretro.so
-)
-
-for core in "${!cores[@]}"; do
-    process_core "$core" "${cores[$core]}"
+for i in "${!cores[@]}"; do
+    process_core "$i" "${cores[$i]}"
 done
